[package]
name = "requin"
version = "0.1.0"
authors = ["James Tan <james_tan97@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
num_enum = "0.5.5"
lazy_static = "1.4.0"
